# Generated by Django 5.1.2 on 2025-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved by an admin.'),
        ),
    ]
