# Generated by Django 5.1.2 on 2025-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resolution_document',
            field=models.FileField(blank=True, help_text='Attach resolution document for this project', null=True, upload_to='project_resolutions/%Y/%m/%d/'),
        ),
    ]
