# Generated by Django 4.2.18 on 2025-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbudget',
            name='beneficiary',
            field=models.CharField(blank=True, help_text='Target beneficiaries of this budget', max_length=255, null=True),
        ),
    ]
